### ISSUE TITLE
terraform import does not populate vdev info

### ISSUE THREAD

**Issue by LnxGnome** [MathiasPius/terraform-provider-zfs#2]
### Terraform Version
```
Terraform v1.4.4
on darwin_amd64
+ provider registry.terraform.io/mathiaspius/zfs v0.3.1
```

### Affected Resource(s)
- zfs

### Terraform Configuration Files
```hcl
resource "zfs_pool" "threepool" {
  name = "threepool"
  mirror {
    device {
      path = "350000c0f04026fac"
    }
    device {
      path = "350000c0f01d1cc2c"
    }
  }
}
```

### Expected Behavior
Imported state should contain vdev info (`mirror` key value should not be empty)
```
          "attributes": {
            "device": [],
            "id": "7532477926929736290",
            "mirror": [],
            "name": "threepool",
            "properties": {
```

### Actual Behavior
vdev info (`mirror` key value) is empty, therefore 
`terraform plan` tries to recreate the pool
`      + mirror { # forces replacement`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
- start with an existing pool, tested with a mirrored disk.
- setup zfs provider
- write simple terraform config, just enough to import the zfs resource
- run the import `terraform import zfs_pool.threepool 7532477926929736290`
- run `terraform plan`

### Important Factoids
Our test pool looks like this
```
zpool status threepool
  pool: threepool
 state: ONLINE
  scan: scrub repaired 0B in 00:01:52 with 0 errors on Sun Jun 26 22:22:32 2022
config:

	NAME                   STATE     READ WRITE CKSUM
	threepool              ONLINE       0     0     0
	  mirror-0             ONLINE       0     0     0
	    350000c0f04026fac  ONLINE       0     0     0
	    350000c0f01d1cc2c  ONLINE       0     0     0

errors: No known data errors
```

### References
https://registry.terraform.io/providers/MathiasPius/zfs/latest/docs
https://github.com/MathiasPius/terraform-provider-zfs

**Comment by MathiasPius** [comment]
Thanks for the thorough bug report. It was definitely an oversight on my part and I've implemented the fix.

Terraform state might be incompatible between the two versions so I've bumped the minor version.

I'm currently trying to get the CI to work again, but once it does I'll push 0.4.0 to the registry :)
